name: karasu_launcher
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  go_router: ^15.1.1
  flutter_riverpod: ^2.6.1
  icons_plus: ^5.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  shelf: ^1.4.2
  http: ^1.3.0
  flutter_html: ^3.0.0-beta.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  file_picker: ^10.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  slang: ^4.7.1
  flutter_dotenv: ^5.2.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  go_router_builder: ^2.8.2

flutter:

  uses-material-design: true
  assets:
  - .env
